// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agents.sql

package database

import (
	"context"
)

const createAgents = `-- name: CreateAgents :one
INSERT INTO agents (id, first_name, last_name, created_at, updated_at, dept)
VALUES (gen_random_uuid, $1, $2, NOW(), NOW(), $3)
RETURNING id, first_name, last_name, created_at, updated_at, dept
`

type CreateAgentsParams struct {
	FirstName string
	LastName  string
	Dept      string
}

func (q *Queries) CreateAgents(ctx context.Context, arg CreateAgentsParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgents, arg.FirstName, arg.LastName, arg.Dept)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dept,
	)
	return i, err
}
