// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agents.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, first_name, last_name, created_at, updated_at, email, dept)
VALUES (gen_random_uuid(), $1, $2, NOW(), NOW(), $3, $4)
RETURNING id, first_name, last_name, created_at, updated_at, email, dept
`

type CreateAgentParams struct {
	FirstName string
	LastName  string
	Email     string
	Dept      string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Dept,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Dept,
	)
	return i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, first_name, last_name, created_at, updated_at, email, dept FROM agents
WHERE id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Dept,
	)
	return i, err
}

const getAllAgents = `-- name: GetAllAgents :many
SELECT id, first_name, last_name, created_at, updated_at, email, dept FROM agents
`

func (q *Queries) GetAllAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, getAllAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.Dept,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :exec
UPDATE agents
SET first_name = $2,
    last_name = $3,
    updated_at = NOW(),
    email = $4,
    dept = $5
WHERE id = $1
`

type UpdateAgentParams struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     string
	Dept      string
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) error {
	_, err := q.db.ExecContext(ctx, updateAgent,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Dept,
	)
	return err
}
