// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dept.sql

package database

import (
	"context"
)

const createDept = `-- name: CreateDept :one
INSERT INTO departments (id, dept_name)
VALUES (gen_random_uuid(), $1)
RETURNING id, dept_name
`

func (q *Queries) CreateDept(ctx context.Context, deptName string) (Department, error) {
	row := q.db.QueryRowContext(ctx, createDept, deptName)
	var i Department
	err := row.Scan(&i.ID, &i.DeptName)
	return i, err
}
