// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: manager.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createManager = `-- name: CreateManager :one
INSERT INTO managers (id, first_name, last_name, email, dept_id)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
RETURNING id, first_name, last_name, email, dept_id
`

type CreateManagerParams struct {
	FirstName string
	LastName  string
	Email     string
	DeptID    uuid.UUID
}

func (q *Queries) CreateManager(ctx context.Context, arg CreateManagerParams) (Manager, error) {
	row := q.db.QueryRowContext(ctx, createManager,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.DeptID,
	)
	var i Manager
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DeptID,
	)
	return i, err
}
