// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Agent struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Dept      string
}

type Customer struct {
	ID         uuid.UUID
	FirstName  string
	LastName   string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Email      string
	Phone      string
	Home       string
	PolicyType string
}

type Department struct {
	ID       uuid.UUID
	DeptName string
}

type Manager struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     string
	DeptID    uuid.UUID
}
